sudo: required
language: elixir
elixir:
  - '1.8.1'
install:
  - mix local.rebar --force; mix local.hex --force; mix deps.get
script:
  - mix test
services:
  - docker
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "2rc5S3VY+iJZW8g+iQjQNmncLzqaxyb45/VOcS3Y2e8WKdKiu6PmIaSxqdt4crp7KMMTiU/i+AYZNU2HvGKb1IC/ij0d+EHjbTGHLo3jxqSZ0EXb8KuF99DrAdepREVzJOYe83J4cczQHGYzopN6LjJ5PhOjK+wWld+7am9Tat9DlOYOxI45CBOXIN6Jvlj9lQdIrX7MH/K3Zc+TGlRWRlSh6cG8tG0XCKX+fFjg9XtdljGLZKz4fJpu+J+3Vg8W2I7Zpo7530hiYL86xJUM8No/2rpm33yJ/mJRAeJDuiZ+9vEmF5vm6CdPeTtH06gzhgNXHFQsIDzrYC2lXGuFuA79st+ICDxB2iOhtFzd6biE5SrxwCVi2vYBfqkGZ+czLh9FY8ZeugHKXa7HB5ZNO0o9W94Jo+3T4/oF8e7THJmjnhd6N92Ze7DSkJhOcUTIxNxuYRsoox3CxHugCWLY+NSt91RBc4VsMPPbn3MeUGVH2RgowjPrBIBX2O1VXtIUO/3eGlqCJOzzwcUV5nfRCRZUi/vWtOiN1yw6ssGp+M14IyLy1y1hvvNXiQPqg2DBGjxtEcXimBq0gzSgtew9lK1O1HUtILfEAYuKTaQGs0e+RwC2uCw9bPhcdadNeXCJHyxjENGP/uljN0CC0bFkGqy4hySIXTa0EoOQIvltywA="
  secret_access_key:
    secure: "CtOTIAJHzKRCrHJxrX7gQEFQvvZwuCZqFGKjaplhdqTrveRegMJubd/7mP47bw3+5PWSE0xthmmXhffXsLpSK4ABs13AFHjHm6uN+nhS613I651S5MuZ2ZjxJjFtnJmlrICmM4mV9Z830y0/Rals4hIRebMR5qu/tVfFmK6RkEHbuk13xiNsjXbwpGJJaXXidjVBve+JnY5S+q9B56jFgrZtOiyf9oqsfoC1ttQ+VGhRyWB3vlZdVzBpbpVK/LbthSjIfcXhAmhQXimlXGyH7R/KotKcgf4iV3djFU0k9+6mjbs3v/QAZh8luljeaxcwwSb3Y9yjszZRV8K9+g1mRJjCg+6Vk9SzDg6bxdmaiG7N/hJf3xFe75Hp2v7t1e5590gqIjXLYsJBFgGfankCzqfnvbFTS+pN8lFam2WN8Cyg2ZbqqIasCeJu06RId5gFpP28/tSPxPQjjWLLSKzoSAkpUD2K8KpGJePFagzWHaQy4P1thWyEiTobNnAr4Ok7WviZWnmSO4l+RFDW2fSOhvDWD/NuCpXpzfcduRqfAa1Xh3nSkoQjeuZO8PzgBvY1ruK5AQvuIJ7U/uvA9etln1V1INypLsF6vvkTT+nqYDmNk+LNOORBF3oCqmLhMz34KvzkOzj+0rM8j9HoACPmZkHxEZtQ7WKtVHKiL4Kk/9k="
  region: "us-east-1"
  app: "crud_app"
  env: "crud-app-dev"
  bucket_name: "elasticbeanstalk-us-east-1-234123676202"
  on:
    branch: master