sudo: required
language: elixir
elixir:
- 1.8.1
before_install:
- npm i -g npm@10.15.0
install:
- mix local.rebar --force; mix local.hex --force; mix deps.get
script:
- mix test
- cd assets && npm install && npm run test:unit
services:
- docker
deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY"
  region: us-east-1
  app: crud_app
  env: crud-app-dev
  bucket_name: elasticbeanstalk-us-east-1-234123676202
  on:
    branch: master
env:
  global:
  - secure: T9jJw/4ngv7/SNocRreVSdZR8jEvQd+mORz9emaF6a9pc26vlk4s+CEiyWdbSlTgXfg5NHgRGY7sinpMZ1w3vL21+veW9rRb8/1/dGVfYZkw/7pxOFbDPCQNsVOGhlopXdptqSGOLLe7RPVGK7GWd7hx33ViAMv9KyhWcU9Pnvmz9BoW8lJ4VlJjwEaEz1gByoE8kPkLmKMhi+z9yPQ1XUrC0M72CeAVgGq27U7LqjLGjWncyr7kML/z1QZ/dZBhrfZzFoL+A0ScpJLoqogo8cCmnJGJZz1WtCfpF3S5DNvD9RiL4Hwa9/IyG8bc5HEQ70CTAw64PriJ24nC15cis3e8mPmP0ALppBzikK9DV9Mkp7+tI9s8tgfSqOCf5fbXaoykiKXpV8FZwbzSzmKPrN2ODuMvbj6k4XTTP9bbG0sQImkAyaqCrSV+PJPQwQ51GUW2nzl1iHB7um+t2koyUqV140HQSIRlTrR8j9a6jc3hMvxaL5E/nY/96BHcvD7Dxec9Gjhri0du7rO+yPkmkm++c/B7c6tOoxft8pjYHclj1oXOtce7vQEIrI1h36rvFK4CYInqTEvx1SpUGaTbq2tvUffTqbNDb2Z2RspD9Xnz0L2ZlLn1DCGuPMk5kfOqy8autPHbBnRNi7sl+W0Zrcy/fLAiDAJIIizSz0XzqMI=
  - secure: ryCs0oOZRS/ec/hqqAm35EwLOAQx46pIe0y5AAcZEzSXXhTlyD/plJX3d/KQrihlKENlvUUNM6XgDZHVi5ySb2Jb7Ok7q+6x6noqkDzslDaaia3tVF7PxywbWNJTZfMD/J6oJlvrODSj1IxL9jFVCN5cn+yq0ky+mZc2D8MQ2RqC5+u2F53Ej1kmjpPH6hahFOnlgFAekwow9ycY6A6v0TjR5gdS2W/UHJnSykfU/Wc59Af2d2sstYqxNO9xAl9ApSrhrr0Cu2o5vwpsmTgAkx2MICQ6H+mCAZkHfkKj1CeS9NOaK6iXqhft6dbOH7QFwtMDBioOQv05GFmnuNEOEHto5Gif4yRtoa4lmexvMnjx85vNBCyAbQ/Mesy2MnN434lwvNmAVbLl8K3zmzXYutJWUekpokaswu6kUurTJ0vyQxVVN+7jPx9aEB3KWTWym2RjcnhEyRQgqh657pEyGBkxFB4Q7nmAxu78w96GbhN8cpmjFblUGJZgLSlswa4l1Smgwg6WhXd150GeLsfeQwQIA5Yr1+tfJzKm0itM1o0gqzCdMxaan5X8tnzuDQ3XnC5xePoUHCoTp+kCuGskDi4guBX8OXM+aeyjq14RP5EROmnf0/nbM+lrdIiXhyd/tl0Dss2nX+GbLc1HIY8uIYCPrXdv84sbdEmf1rYr5ZY=
