version: '3.5'

services:
  app:
    depends_on:
      - postgres
    image: "crud_app:latest"
    ports:
      - "80:4000"
    env_file:
      - rel.env
    command: bash -c "/opt/app/bin/crud_app foreground"
    
  postgres:
    image: postgres:11
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - rel.env

volumes:
  pgdata: