version: '3.5'

volumes:
  pgdata:

services:
  web:
    image: elixir:1.8.1-alpine
    env_file:
      - config/docker.env
    environment:
      PGHOST: db
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    build: .

  db:
    image: postgres:11
    env_file:
      - config/docker.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always